# Generated by Django 5.0.3 on 2025-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('perfil', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Trabajador'), (3, 'Jefe de Sección')])),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('hash', models.CharField(editable=False, max_length=128)),
            ],
        ),
    ]
