# Generated by Django 5.0.3 on 2025-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva2LopezJorge_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Trabajador'), (3, 'Jefe de Sección')]),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
