# Generated by Django 5.0.3 on 2025-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'afps',
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'descuentos',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('base', models.IntegerField()),
                ('afp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Liquidaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('sbase', models.IntegerField(default=0)),
                ('sbruto', models.IntegerField(default=0)),
                ('desc_afp', models.IntegerField(default=0)),
                ('descuentos', models.IntegerField(default=0)),
                ('descuentos_totales', models.IntegerField(default=0)),
                ('sueldo_liquido', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'liquidaciones',
                'unique_together': {('rut', 'mes', 'anio')},
            },
        ),
    ]
