# Generated by Django 5.0.3 on 2025-12-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva2Trabajador_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liquidaciones',
            table=None,
        ),
    ]
