# Generated by Django 5.0.3 on 2025-12-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva2Trabajador_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='afp',
            field=models.ForeignKey(db_column='afp_id', on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='eva2Trabajador_app.afps'),
        ),
        migrations.AlterModelTable(
            name='afps',
            table='eva2trabajador_app_afp',
        ),
        migrations.AlterModelTable(
            name='descuentos',
            table='eva2trabajador_app_descuento',
        ),
        migrations.AlterModelTable(
            name='liquidaciones',
            table='eva2trabajador_app_liquidaciones',
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='eva2trabajador_app_trabajador',
        ),
    ]
